#!/bin/bash

# Check for changes in Go files
if git diff --cached --name-only | grep -q '\.go$'; then
    echo "Go files detected. Running tests..."

    # Run tests
    go test -v ./cmd
    echo ""

    # Check the exit status of the tests
    if [ $? -ne 0 ]; then
        echo "Tests failed. Push cancelled."
        exit 1
    fi
else
    echo -e  "No Go files changed. Skipping tests.\n"
fi

