#!/bin/sh

# Check for changes in Go files
if git diff --cached --name-only | grep -q '\.go$'; then
    echo "Formatting Go files..."
    gofmt -w .

    # Add formatted files to the staging area
    git add .
else
    echo "No Go files changed. Skipping formatting."
fi

