#!/bin/sh

# Check for changes in Go files
if git diff --cached --name-only | grep -q '\.go$'; then
    echo "Formatting Go files..."
    gofmt -w .
    echo ""

    # Add formatted files to the staging area
    git add .
else
    echo -e "No Go files changed. Skipping formatting.\n"
fi

